name: Publish every commit to pkg.pr.new
on:
   pull_request:
   push:
      branches: main
      branches-ignore: changeset-release/**
      tags:
         - "!**"

jobs:
   build:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [20.x]

      steps:
         - name: Checkout repo
           uses: actions/checkout@v4

         - name: Setup pnpm
           uses: pnpm/action-setup@v4
           with:
              version: 9.7.0

         - name: Setup Node.js 20.x
           uses: actions/setup-node@v4
           with:
              node-version: ${{ matrix.node-version }}
              cache: "pnpm"

         - name: Install dependencies and build
           run: |
              pnpm install --frozen-lockfile
              pnpm build

         - name: Deploy and test release via pkg.pr.new
           run: pnpm test:release
